---
kind: Service
apiVersion: v1
metadata:
  name: web-shell
spec:
  selector:
    app: web-shell
  ports:
    - port: 80
      targetPort: 2020
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: web-shell
  name: web-shell
spec:
  serviceName: web-shell
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: web-shell
  template:
    metadata:
      labels:
        app: web-shell
    spec:
      containers:
      - env:
        - name: HOST
          value: 0.0.0.0
        - name: PORT
          value: "2020"
        - name: USER
          value: webshell
        - name: PASSWORD
          value: webshell123
        image: ghcr.io/eumel8/web-shell/web-shell:container
        imagePullPolicy: Always
        name: web-shell
        resources:
          limits:
            cpu: 1000m
            memory: 1024Mi
          requests:
            cpu: 100m
            memory: 128Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: true
          runAsUser: 1000
          runAsGroup: 1000
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - name: workdir
          mountPath: /home/webshell
        - name: tmp
          mountPath: /tmp
      dnsPolicy: ClusterFirst
      hostNetwork: false
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 1000
        supplementalGroups:
        - 1000
      terminationGracePeriodSeconds: 3
      serviceAccountName: web-shell
      volumes:
      - name: workdir
        emptyDir: {}
      - name: tmp
        emptyDir:
          medium: Memory
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: web-shell
  name: web-shell
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    app: web-shell
  name: web-shell
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app: web-shell
  name: web-shell
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: web-shell
subjects:
  - kind: ServiceAccount
    name: web-shell
